### ISSUE TITLE
Piwigo with an Apache reverse proxy -> links broken

### ISSUE THREAD

**Issue by cybermcm** [mathieuruellan/docker-piwigo#16]
I'm trying to use this docker image with an Apache reverse proxy and a subpath, e.g. https://xyz.net/piwigo.
It works but not all of it. A lot of icons are broken and some links too. E.g. when I log in I'm getting redirected to the wrong url. Start page -> log in -> redirection to https://xyz.net instead of https://xyz.net/piwigo

docker compose file:
```
piwigo:
  depends_on:
   - sql
  image: mathieuruellan/piwigo
  container_name: piwigo
  restart: always
  ports:
   - "127.0.0.1:20008:80"
  volumes:
   - /etc/timezone:/etc/timezone:ro
   - /etc/localtime:/etc/localtime:ro
   - /home/piwigo/data/galleries:/var/www/galleries
   - /home/piwigo/data/local:/var/www/local
   - /home/piwigo/data/plugins:/var/www/plugins
   - /home/piwigo/data/themes:/var/www/themes
   - /home/piwigo/cache:/var/www/_data/i
   - /home/piwigo/upload:/var/www/upload
   - /home/piwigo/log/var:/var/log
   - /home/piwigo/log/piwigo:/var/log/apache2
  networks:
   - sql
```
relevant apache config:
```
RewriteRule ^/piwigo$ /piwigo/ [R,L]
ProxyPass "/piwigo" "http://localhost:20008"
ProxyPassReverse "/piwigo" "http://localhost:20008"
```
Any ideas how to get this config working?

**Comment by mathieuruellan** [comment]
Hi, 

I succeed with nginx. First time, you have to connect with `http://localhost/piwigo/install.php`

Here is my docker-compose.yml

```
mysqlpiwigo:
   image: mysql:5.5
   volumes:
      - /home/piwigo/mysql/:/var/lib/mysql
   environment:
      - MYSQL_ROOT_PASSWORD=MYROOTPASSWORD
      - MYSQL_DATABASE=piwigo
      - MYSQL_USER=piwigo
      - MYSQL_PASSWORD=MYUSERPASSWORD
nginx: 
  image: nginx:latest
  container_name: production_nginx
  volumes:
    - ./nginx.conf:/etc/nginx/conf.d/default.conf
  links:
    - piwigo  
  ports:
    - 80:80
    - 443:443

piwigo:
   image: mathieuruellan/piwigo
   links:
      - mysqlpiwigo:mysql
   volumes:
      - /home/piwigo/data/galleries:/var/www/galleries
      - /home/piwigo/data/local:/var/www/local
      - /home/piwigo/data/plugins:/var/www/plugins
      - /home/piwigo/data/themes:/var/www/themes
      - /home/piwigo/cache:/var/www/_data/i
      - /home/piwigo/upload:/var/www/upload
      - /var/log
      - /var/log/piwigo:/var/log/apache2
   hostname: piwigo
   domainname: MYDOMAIN.COM
```

Here nginx.conf:

```
server {
        listen 80 default_server;
        listen [::]:80 default_server;

        # SSL configuration
        #
        # listen 443 ssl default_server;
        # listen [::]:443 ssl default_server;
        #
        # Note: You should disable gzip for SSL traffic.
        # See: https://bugs.debian.org/773332
        #
        # Read up on ssl_ciphers to ensure a secure configuration.
        # See: https://bugs.debian.org/765782
        #
        # Self signed certs generated by the ssl-cert package
        # Don't use them in a production server!
        #
        # include snippets/snakeoil.conf;

        server_name _;

        location /piwigo {
            proxy_pass http://piwigo:80/;   
        }

        # pass the PHP scripts to FastCGI server listening on 127.0.0.1:9000
        #
        #location ~ \.php$ {
        #       include snippets/fastcgi-php.conf;
        #
        #       # With php7.0-cgi alone:
        #       fastcgi_pass 127.0.0.1:9000;
        #       # With php7.0-fpm:
        #       fastcgi_pass unix:/run/php/php7.0-fpm.sock;
        #}

        # deny access to .htaccess files, if Apache's document root
        # concurs with nginx's one
        #
        #location ~ /\.ht {
        #       deny all;
        #}
}
```
