### ISSUE TITLE
"Cannot connect to server" error on setup

### ISSUE THREAD

**Issue by nickdos** [mathieuruellan/docker-piwigo#19]
Same issue as #2. That issue was resolved by the user with no indication of how they fixed it, so opening a new issue.

When I start Docker using `docker-compose up -d` with my edited `docker-compose.yml` file, I get the setup screen (http://localhost:8088/install.php) and I enter the info from my compose file for database creds, I get the error "Cannot connect to server". 

I've tried the following values for database host:
- localhost
- piwigo
- mysqlpiwigo
- mysql
- 127.0.0.1
- IP address of `mysqlpiwigo` container
- IP address of `piwigo` container

I've run out of ideas now - I'm probably missing something obvious, so apologies in advanced if so.

My docker-compose.yml file:
```yml
mysqlpiwigo:
   image: mysql:5.5
   volumes:
      - /data/piwigo/mysql/:/var/lib/mysql
   environment:
      - MYSQL_ROOT_PASSWORD=xxxxxx
      - MYSQL_DATABASE=piwigo
      - MYSQL_USER=piwigo
      - MYSQL_PASSWORD=piwigo
piwigo:
   image: mathieuruellan/piwigo
   links:
      - mysqlpiwigo:mysql
   volumes:
      - /data/piwigo/data/galleries:/var/www/galleries
      - /data/piwigo/data/local:/var/www/local
      - /data/piwigo/data/plugins:/var/www/plugins
      - /data/piwigo/data/themes:/var/www/themes
      - /data/piwigo/cache:/var/www/_data/i
      - /data/piwigo/upload:/var/www/upload
      - /data/var/log
      - /data/var/log/piwigo:/var/log/apache2
   ports:
      - "8088:80"
   hostname: piwigo
   #domainname: 

```
FYI, I've checked my volume mapping and I can see the database files in `/data/piwigo/mysql`. I've tried adding a `domainname` value and specifying it as well, to no avail.
