### ISSUE TITLE
http error 500

### ISSUE THREAD

**Issue by st0nec0ld** [mathieuruellan/docker-piwigo#31]
i try your docker-compose.yml

```
services:
  mariadb:
    image: mariadb:latest
    volumes:
        - ./piwigo/mysql/:/var/lib/mysql
    environment:
        - MARIADB_ROOT_PASSWORD=piwigo
        - MARIADB_DATABASE=piwigo
        - MARIADB_USER=piwigo
        - MARIADB_PASSWORD=piwigo
  piwigo:
    image: mathieuruellan/piwigo:12.3.0
    environment:
        - BASH_MODE=set -e
    depends_on:
        - mariadb
    volumes:
        - ./piwigo/data/galleries:/var/www/galleries
        - ./piwigo/data/local:/var/www/local
        - ./piwigo/data/plugins:/var/www/plugins
        - ./piwigo/data/themes:/var/www/themes
        - ./piwigo/cache:/var/www/_data/i
        - ./piwigo/upload:/var/www/upload
        - ./var/log:/var/log
        - ./var/log/piwigo:/var/log/apache2
    ports:
        - "9999:80"
    hostname: localhost
    domainname: mydomain
```

```
stone@l337:~/piwigo$ ls -l
total 12
-rw-rw-r-- 1 stone stone  828 Aug 21 21:44 docker-compose.yml
drwxrwxrwx 6 stone stone 4096 Aug 21 21:44 piwigo
drwxr-xr-x 3 root  root  4096 Aug 21 21:44 var
```

i can access the install page, after that it shows http error 500. any advice?
![image](https://github.com/mathieuruellan/docker-piwigo/assets/21226229/d6a1a9b4-6549-408a-971e-e4cad3616ccd)

*edit* my this helps?

`[Mon Aug 21 20:11:08.896813 2023] [php:error] [pid 28] [client 192.168.178.43:64660] PHP Fatal error:  Uncaught Error: Call to a member function set_charset() on null in /var/www/include/dblayer/functions_mysqli.inc.php:88\nStack trace:\n#0 /var/www/install.php(261): pwg_db_check_charset()\n#1 {main}\n  thrown in /var/www/include/dblayer/functions_mysqli.inc.php on line 88, referer: http://192.168.178.73:9999/install.php`
